"""
Compatibility tests for the AES-GCM-SIV migration from the custom rfc8452.py
implementation (using pyaesni) to the cryptography library's AESGCMSIV.

These tests verify that the AES_GCM_SIV wrapper class in rfc8452.py produces
correct results by checking against:
  1. RFC 8452 Appendix C known-answer test vectors (256-bit key)
  2. Golden ciphertexts generated by the original implementation
  3. Round-trip encrypt/decrypt correctness
  4. Error handling (ValueError on auth failure)
  5. Edge cases (empty plaintext, empty AAD, various data sizes)

Note: The PDDB only uses 256-bit keys. The old pyaesni-based implementation
only supported 256-bit keys (cbc256_encrypt), so 128-bit key tests are not
included.

Run with: python -m pytest test_aes_gcm_siv_migration.py -v
    or:   python test_aes_gcm_siv_migration.py
"""

import sys
import os
import unittest

# Ensure the tools directory is on the path so we can import rfc8452
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from rfc8452 import AES_GCM_SIV


class TestRfc8452AppendixC256NoAad(unittest.TestCase):
    """RFC 8452 Appendix C.2: AEAD_AES_256_GCM_SIV test vectors (no AAD).

    These vectors pass against both the old pyaesni-based implementation and
    the new cryptography-based implementation.
    """

    def test_vector_256bit_empty_pt_empty_aad(self):
        """C.2 first vector: empty plaintext, empty AAD, 256-bit key."""
        key = bytes.fromhex(
            '01000000000000000000000000000000'
            '00000000000000000000000000000000'
        )
        nonce = bytes.fromhex('030000000000000000000000')
        expected = bytes.fromhex('07f5f4169bbf55a8400cd47ea6fd400f')

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'', b'')
        self.assertEqual(ct, expected)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'')
        self.assertEqual(pt, b'')

    def test_vector_256bit_8byte_pt(self):
        """C.2 second vector: 8-byte plaintext, no AAD, 256-bit key."""
        key = bytes.fromhex(
            '01000000000000000000000000000000'
            '00000000000000000000000000000000'
        )
        nonce = bytes.fromhex('030000000000000000000000')
        plaintext = bytes.fromhex('0100000000000000')
        expected = bytes.fromhex(
            'c2ef328e5c71c83b843122130f7364b7'
            '61e0b97427e3df28'
        )

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(plaintext, b'')
        self.assertEqual(ct, expected)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'')
        self.assertEqual(pt, plaintext)


class TestRfc8452AppendixC256WithAad(unittest.TestCase):
    """RFC 8452 Appendix C.2: AEAD_AES_256_GCM_SIV test vectors WITH AAD.

    These vectors verify RFC-correct behavior. The new cryptography-based
    implementation must pass these. The old pyaesni-based implementation had
    known deviations from the RFC for the encrypt path (it used cbc256_encrypt
    with a zero IV to emulate ECB, which produces incorrect results for some
    inputs). Decrypt round-trips still worked because both paths used the same
    (incorrect) primitive consistently.
    """

    def test_vector_256bit_with_aad(self):
        """C.2 vector with AAD: 8-byte AAD, 8-byte plaintext, 256-bit key."""
        key = bytes.fromhex(
            '01000000000000000000000000000000'
            '00000000000000000000000000000000'
        )
        nonce = bytes.fromhex('030000000000000000000000')
        aad = bytes.fromhex('0100000000000000')
        plaintext = bytes.fromhex('0200000000000000')
        expected = bytes.fromhex(
            '1de22967237a813291213f267e3b452f'
            '02d01ae33e4ec854'
        )

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(plaintext, aad)
        self.assertEqual(ct, expected)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, aad)
        self.assertEqual(pt, plaintext)

    def test_vector_256bit_with_12byte_aad(self):
        """C.2 vector: 12-byte AAD, 12-byte plaintext, 256-bit key."""
        key = bytes.fromhex(
            '01000000000000000000000000000000'
            '00000000000000000000000000000000'
        )
        nonce = bytes.fromhex('030000000000000000000000')
        aad = bytes.fromhex('010000000000000000000000')
        plaintext = bytes.fromhex('020000000000000000000000')
        expected = bytes.fromhex(
            '91c6b0c0a36024bead310795a8e62e6d'
            'f9f09ff3d16f3f6dfcc1b57c8419c84a'
        )

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(plaintext, aad)
        self.assertEqual(ct, expected)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, aad)
        self.assertEqual(pt, plaintext)

    def test_vector_256bit_with_20byte_aad(self):
        """C.2 vector: 20-byte AAD, 18-byte plaintext, 256-bit key."""
        key = bytes.fromhex(
            '01000000000000000000000000000000'
            '00000000000000000000000000000000'
        )
        nonce = bytes.fromhex('030000000000000000000000')
        aad = bytes.fromhex('0100000000000000000000000000000002000000')
        plaintext = bytes.fromhex('030000000000000000000000000000000400')
        expected = bytes.fromhex(
            'b43140a7e1fa5ac6f25a16a05aca0f87'
            '66ec6e46fd254054a7759da0be064ad0'
            '9c1a'
        )

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(plaintext, aad)
        self.assertEqual(ct, expected)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, aad)
        self.assertEqual(pt, plaintext)


class TestGoldenVectors(unittest.TestCase):
    """Golden ciphertexts generated by the original pyaesni-based implementation.

    These test vectors were captured from the old rfc8452.py before migration
    to ensure byte-for-byte compatibility.
    """

    KEY256 = bytes.fromhex(
        '0100000000000000000000000000000002000000000000000000000000000000'
    )
    NONCE1 = bytes.fromhex('030000000000000000000000')
    NONCE2 = bytes.fromhex('aabbccddee00112233445566')

    def test_golden_simple_encrypt_decrypt(self):
        """256-bit key, 16-byte plaintext, 13-byte AAD."""
        cipher = AES_GCM_SIV(self.KEY256, self.NONCE1)
        ct = cipher.encrypt(b'hello world test', b'aad data here')
        self.assertEqual(
            ct.hex(),
            '6cd94d28247177c3c28e42b24884762c254366249d38b7c000d4f017fa31bc65'
        )

        cipher2 = AES_GCM_SIV(self.KEY256, self.NONCE1)
        pt = cipher2.decrypt(ct, b'aad data here')
        self.assertEqual(pt, b'hello world test')

    def test_golden_empty_plaintext(self):
        """256-bit key, empty plaintext, 8-byte AAD."""
        cipher = AES_GCM_SIV(self.KEY256, self.NONCE1)
        ct = cipher.encrypt(b'', b'only aad')
        self.assertEqual(ct.hex(), '3bca95b308dd8b7bd2e5b59743747c1b')
        self.assertEqual(len(ct), 16)  # tag only

        cipher2 = AES_GCM_SIV(self.KEY256, self.NONCE1)
        pt = cipher2.decrypt(ct, b'only aad')
        self.assertEqual(pt, b'')

    def test_golden_empty_aad(self):
        """256-bit key, 16-byte plaintext, empty AAD."""
        cipher = AES_GCM_SIV(self.KEY256, self.NONCE1)
        ct = cipher.encrypt(b'data without aad', b'')
        self.assertEqual(
            ct.hex(),
            '7777c78bca20a2bc5cdf4cb631e4512a531a81ff8f36b05115e3100c1ea800dc'
        )

        cipher2 = AES_GCM_SIV(self.KEY256, self.NONCE1)
        pt = cipher2.decrypt(ct, b'')
        self.assertEqual(pt, b'data without aad')

    def test_golden_large_data_pddb_page(self):
        """256-bit key, 4096-byte plaintext simulating a PDDB page, with basis AAD."""
        large_data = bytes(range(256)) * 16  # 4096 bytes
        # Simulates basis_aad('.System', version=0x0201, dna=0)
        large_aad = (
            b'.System'
            + (0x0201).to_bytes(4, 'little')
            + (0).to_bytes(8, 'little')
        )

        cipher = AES_GCM_SIV(self.KEY256, self.NONCE1)
        ct = cipher.encrypt(large_data, large_aad)

        self.assertEqual(len(ct), 4096 + 16)  # data + tag
        self.assertEqual(
            ct[:32].hex(),
            '562fc26c66c5c533dcb0a62f95e4e245065763d58fe8a3bf6a1e1fb740b6f7bb'
        )
        self.assertEqual(
            ct[-32:].hex(),
            'daa87c3ddb33792e1280947cedb5e39f6fdfee2e6bcf4ae3b99659f01d65f9e1'
        )

        cipher2 = AES_GCM_SIV(self.KEY256, self.NONCE1)
        pt = cipher2.decrypt(ct, large_aad)
        self.assertEqual(pt, large_data)

    def test_golden_different_nonce(self):
        """256-bit key, different nonce produces different ciphertext."""
        cipher = AES_GCM_SIV(self.KEY256, self.NONCE2)
        ct = cipher.encrypt(b'different nonce', b'test')
        self.assertEqual(
            ct.hex(),
            '3cac834e2083062e518401e7122c0a96cd12e4f76b57227397aa63b3a12cdc'
        )

        cipher2 = AES_GCM_SIV(self.KEY256, self.NONCE2)
        pt = cipher2.decrypt(ct, b'test')
        self.assertEqual(pt, b'different nonce')


class TestErrorHandling(unittest.TestCase):
    """Verify that authentication failures raise ValueError."""

    KEY = bytes.fromhex(
        '0100000000000000000000000000000002000000000000000000000000000000'
    )
    NONCE = bytes.fromhex('030000000000000000000000')

    def _get_valid_ciphertext(self):
        cipher = AES_GCM_SIV(self.KEY, self.NONCE)
        return cipher.encrypt(b'test plaintext!!', b'test aad')

    def test_tampered_ciphertext_raises_valueerror(self):
        """Flipping a bit in ciphertext must raise ValueError."""
        ct = self._get_valid_ciphertext()
        tampered = bytearray(ct)
        tampered[0] ^= 0xFF
        cipher = AES_GCM_SIV(self.KEY, self.NONCE)
        with self.assertRaises(ValueError):
            cipher.decrypt(bytes(tampered), b'test aad')

    def test_tampered_tag_raises_valueerror(self):
        """Flipping a bit in the tag must raise ValueError."""
        ct = self._get_valid_ciphertext()
        tampered = bytearray(ct)
        tampered[-1] ^= 0x01  # flip last bit of tag
        cipher = AES_GCM_SIV(self.KEY, self.NONCE)
        with self.assertRaises(ValueError):
            cipher.decrypt(bytes(tampered), b'test aad')

    def test_wrong_aad_raises_valueerror(self):
        """Using wrong AAD for decryption must raise ValueError."""
        ct = self._get_valid_ciphertext()
        cipher = AES_GCM_SIV(self.KEY, self.NONCE)
        with self.assertRaises(ValueError):
            cipher.decrypt(ct, b'wrong aad')

    def test_wrong_key_raises_valueerror(self):
        """Using wrong key for decryption must raise ValueError."""
        ct = self._get_valid_ciphertext()
        wrong_key = bytes(32)  # all zeros
        cipher = AES_GCM_SIV(wrong_key, self.NONCE)
        with self.assertRaises(ValueError):
            cipher.decrypt(ct, b'test aad')

    def test_wrong_nonce_raises_valueerror(self):
        """Using wrong nonce for decryption must raise ValueError."""
        ct = self._get_valid_ciphertext()
        wrong_nonce = bytes(12)  # all zeros
        cipher = AES_GCM_SIV(self.KEY, wrong_nonce)
        with self.assertRaises(ValueError):
            cipher.decrypt(ct, b'test aad')

    def test_truncated_ciphertext_raises(self):
        """Ciphertext shorter than 16 bytes (tag) must raise."""
        cipher = AES_GCM_SIV(self.KEY, self.NONCE)
        with self.assertRaises((ValueError, Exception)):
            cipher.decrypt(b'\x00' * 15, b'')


class TestEdgeCases(unittest.TestCase):
    """Edge case tests for the AES_GCM_SIV wrapper."""

    def test_256bit_key(self):
        """Verify 256-bit keys work correctly."""
        key = bytes(32)
        nonce = bytes(12)
        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'256-bit key test', b'aad')

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'aad')
        self.assertEqual(pt, b'256-bit key test')

    def test_256bit_key_nonzero(self):
        """Verify 256-bit keys with non-zero values."""
        key = bytes(range(32))
        nonce = bytes(range(12))
        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'nonzero key test', b'aad')

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'aad')
        self.assertEqual(pt, b'nonzero key test')

    def test_both_empty(self):
        """Empty plaintext and empty AAD."""
        key = bytes(32)
        nonce = bytes(12)
        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'', b'')
        self.assertEqual(len(ct), 16)  # just the tag

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'')
        self.assertEqual(pt, b'')

    def test_single_byte_plaintext(self):
        """Single byte of plaintext."""
        key = bytes(32)
        nonce = bytes(12)
        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'\x42', b'aad')
        self.assertEqual(len(ct), 1 + 16)  # 1 byte ct + 16 byte tag

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, b'aad')
        self.assertEqual(pt, b'\x42')

    def test_non_block_aligned_plaintext(self):
        """Plaintext not a multiple of 16 bytes."""
        key = bytes(32)
        nonce = bytes(12)
        for pt_len in [1, 7, 15, 17, 31, 33, 100, 255]:
            plaintext = bytes(range(pt_len % 256)) * (pt_len // 256 + 1)
            plaintext = plaintext[:pt_len]

            cipher = AES_GCM_SIV(key, nonce)
            ct = cipher.encrypt(plaintext, b'aad')
            self.assertEqual(len(ct), pt_len + 16)

            cipher2 = AES_GCM_SIV(key, nonce)
            pt = cipher2.decrypt(ct, b'aad')
            self.assertEqual(pt, plaintext)

    def test_large_aad(self):
        """Large AAD (1KB)."""
        key = bytes(32)
        nonce = bytes(12)
        aad = bytes(range(256)) * 4  # 1024 bytes of AAD

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(b'test', aad)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, aad)
        self.assertEqual(pt, b'test')

    def test_ciphertext_length(self):
        """Ciphertext is always plaintext_length + 16 (tag)."""
        key = bytes(32)
        nonce = bytes(12)
        for pt_len in [0, 1, 15, 16, 17, 100, 1000, 4096]:
            plaintext = b'\xAB' * pt_len
            cipher = AES_GCM_SIV(key, nonce)
            ct = cipher.encrypt(plaintext, b'')
            self.assertEqual(
                len(ct), pt_len + 16,
                f"Wrong ciphertext length for {pt_len}-byte plaintext"
            )

    def test_different_nonces_different_ciphertexts(self):
        """Same key + plaintext + AAD but different nonces must produce different ciphertexts."""
        key = bytes(32)
        plaintext = b'same plaintext'
        aad = b'same aad'
        results = set()
        for i in range(10):
            nonce = i.to_bytes(12, 'big')
            cipher = AES_GCM_SIV(key, nonce)
            ct = cipher.encrypt(plaintext, aad)
            results.add(ct)
        self.assertEqual(len(results), 10, "Different nonces must produce different ciphertexts")


class TestPddbUsagePatterns(unittest.TestCase):
    """Tests that mirror actual PDDB usage patterns from pddbcommon.py."""

    def test_keycommit_decrypt_pattern(self):
        """Simulates the keycommit_decrypt pattern from pddbcommon.py.

        The pattern: extract nonce from first 12 bytes, ciphertext from
        middle, tag from last 16 bytes, then decrypt.
        """
        key = bytes.fromhex(
            'deadbeefcafebabe0102030405060708'
            '1112131415161718212223242526272800'
        )[:32]
        nonce = bytes(range(12))
        plaintext = b'A' * 4004  # typical PDDB page data size

        # Encrypt
        cipher = AES_GCM_SIV(key, nonce)
        ct_with_tag = cipher.encrypt(plaintext, b'test_basis\x01\x02\x00\x00')

        # Simulate how pddbcommon.py stores/retrieves: nonce || ct || tag
        stored = nonce + ct_with_tag

        # Decrypt using the PDDB pattern
        extracted_nonce = stored[:12]
        ct_and_tag = stored[12:]
        cipher2 = AES_GCM_SIV(key, extracted_nonce)
        recovered = cipher2.decrypt(ct_and_tag, b'test_basis\x01\x02\x00\x00')
        self.assertEqual(recovered, plaintext)

    def test_basis_aad_pattern(self):
        """Tests with AAD constructed like basis_aad() in pddbcommon.py."""
        key = bytes(32)
        nonce = bytes(12)
        VERSION = 0x0201
        DNA = 0

        # Construct AAD the same way pddbcommon.basis_aad() does
        name = '.System'
        aad = bytearray(name, 'utf-8')
        aad += VERSION.to_bytes(4, 'little')
        aad += DNA.to_bytes(8, 'little')
        aad = bytes(aad)

        plaintext = b'\x00' * 4064  # VPAGE_SIZE worth of data

        cipher = AES_GCM_SIV(key, nonce)
        ct = cipher.encrypt(plaintext, aad)

        cipher2 = AES_GCM_SIV(key, nonce)
        pt = cipher2.decrypt(ct, aad)
        self.assertEqual(pt, plaintext)

    def test_page_decrypt_pattern(self):
        """Simulates per-page decrypt as done in PDDB: nonce is first 12 bytes of page."""
        key = bytes(32)

        # Simulate an encrypted page: nonce (12) + ct (4064) + tag (16) = 4092
        # But actually pages are 4096 total: 12 nonce + rest is ct+tag
        nonce = bytes(range(12))
        page_data = b'\xAB' * (4096 - 12 - 16)  # plaintext portion

        cipher = AES_GCM_SIV(key, nonce)
        ct_with_tag = cipher.encrypt(page_data, b'.System\x01\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')

        # Full page as stored on disk
        full_page = nonce + ct_with_tag
        self.assertEqual(len(full_page), 4096)

        # Decrypt using page pattern
        cipher2 = AES_GCM_SIV(key, full_page[:12])
        pt = cipher2.decrypt(full_page[12:], b'.System\x01\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
        self.assertEqual(pt, page_data)


if __name__ == '__main__':
    unittest.main(verbosity=2)
